#!/bin/bash

echo "🔍 检查操作日志表..."

# 使用 Prisma Studio 查看数据
echo "📊 打开 Prisma Studio 查看 sys_oper_log 表"
echo ""
echo "运行命令:"
echo "  npx prisma studio"
echo ""
echo "然后在浏览器中:"
echo "  1. 找到 sys_oper_log 表"
echo "  2. 查看最新的记录"
echo "  3. 检查 title 字段是否为 '用户管理'"
echo ""
echo "或者使用 Prisma Client 查询:"
echo ""
echo "node -e \""
echo "const { PrismaClient } = require('@prisma/client');"
echo "const prisma = new PrismaClient();"
echo "prisma.sysOperLog.findMany({"
echo "  take: 5,"
echo "  orderBy: { operTime: 'desc' }"
echo "}).then(logs => {"
echo "  console.log('最近的操作日志:');"
echo "  logs.forEach(log => {"
echo "    console.log(\\\`- \\\${log.title} by \\\${log.operName} at \\\${log.operTime}\\\`);"
echo "  });"
echo "  prisma.\\\$disconnect();"
echo "});"
echo "\""
